# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='galaxy',
  serialized_pb='\n\ntask.proto\x12\x06galaxy\"-\n\nTaskStatus\x12\x0f\n\x07task_id\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\x05\"\xc8\x01\n\x08TaskInfo\x12\x0f\n\x07task_id\x18\x01 \x01(\x03\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x10\n\x08task_raw\x18\x03 \x01(\x0c\x12\x10\n\x08\x63md_line\x18\x04 \x01(\t\x12\x14\n\x0crequired_cpu\x18\x05 \x01(\x01\x12\x14\n\x0crequired_mem\x18\x06 \x01(\x03\x12\x18\n\x10\x66\x61il_retry_times\x18\x07 \x01(\x05\x12\x13\n\x0btask_offset\x18\x08 \x01(\x05\x12\x19\n\x11job_replicate_num\x18\t \x01(\x05*Y\n\tTaskState\x12\r\n\tDEPLOYING\x10\x00\x12\x0b\n\x07RUNNING\x10\x02\x12\n\n\x06KILLED\x10\x03\x12\x0b\n\x07RESTART\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x12\x0c\n\x08\x43OMPLETE\x10\x06')

_TASKSTATE = _descriptor.EnumDescriptor(
  name='TaskState',
  full_name='galaxy.TaskState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEPLOYING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KILLED', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESTART', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=272,
  serialized_end=361,
)

TaskState = enum_type_wrapper.EnumTypeWrapper(_TASKSTATE)
DEPLOYING = 0
RUNNING = 2
KILLED = 3
RESTART = 4
ERROR = 5
COMPLETE = 6



_TASKSTATUS = _descriptor.Descriptor(
  name='TaskStatus',
  full_name='galaxy.TaskStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='galaxy.TaskStatus.task_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='galaxy.TaskStatus.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=67,
)


_TASKINFO = _descriptor.Descriptor(
  name='TaskInfo',
  full_name='galaxy.TaskInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='galaxy.TaskInfo.task_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_name', full_name='galaxy.TaskInfo.task_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_raw', full_name='galaxy.TaskInfo.task_raw', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd_line', full_name='galaxy.TaskInfo.cmd_line', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required_cpu', full_name='galaxy.TaskInfo.required_cpu', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required_mem', full_name='galaxy.TaskInfo.required_mem', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fail_retry_times', full_name='galaxy.TaskInfo.fail_retry_times', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_offset', full_name='galaxy.TaskInfo.task_offset', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_replicate_num', full_name='galaxy.TaskInfo.job_replicate_num', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=270,
)

DESCRIPTOR.message_types_by_name['TaskStatus'] = _TASKSTATUS
DESCRIPTOR.message_types_by_name['TaskInfo'] = _TASKINFO

class TaskStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKSTATUS

  # @@protoc_insertion_point(class_scope:galaxy.TaskStatus)

class TaskInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKINFO

  # @@protoc_insertion_point(class_scope:galaxy.TaskInfo)


# @@protoc_insertion_point(module_scope)
