# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: initd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import galaxy_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='initd.proto',
  package='baidu.galaxy',
  serialized_pb=_b('\n\x0binitd.proto\x12\x0c\x62\x61idu.galaxy\x1a\x0cgalaxy.proto\"I\n\x15ProcessInfoCheckpoint\x12\x30\n\rprocess_infos\x18\x01 \x03(\x0b\x32\x19.baidu.galaxy.ProcessInfo\"g\n\x0bProcessInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12+\n\x06status\x18\x03 \x01(\x0e\x32\x1b.baidu.galaxy.ProcessStatus\x12\x11\n\texit_code\x18\x04 \x01(\x05\"&\n\x17GetProcessStatusRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"l\n\x18GetProcessStatusResponse\x12*\n\x07process\x18\x01 \x01(\x0b\x32\x19.baidu.galaxy.ProcessInfo\x12$\n\x06status\x18\x02 \x01(\x0e\x32\x14.baidu.galaxy.Status\"4\n\nCgroupPath\x12\x11\n\tsubsystem\x18\x01 \x01(\t\x12\x13\n\x0b\x63group_path\x18\x02 \x01(\t\"\xc0\x01\n\x0e\x45xecuteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08\x63ommands\x18\x02 \x01(\t\x12\x0c\n\x04\x65nvs\x18\x03 \x03(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x13\n\x0b\x63group_path\x18\x05 \x01(\t\x12\x0c\n\x04user\x18\x06 \x01(\t\x12\x10\n\x08pty_file\x18\x07 \x01(\t\x12\x13\n\x0b\x63hroot_path\x18\x08 \x01(\t\x12)\n\x07\x63groups\x18\t \x03(\x0b\x32\x18.baidu.galaxy.CgroupPath\"Q\n\x0f\x45xecuteResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12$\n\x06status\x18\x03 \x01(\x0e\x32\x14.baidu.galaxy.Status*e\n\rProcessStatus\x12\x13\n\x0fkProcessRunning\x10\x00\x12\x15\n\x11kProcessTerminate\x10\x01\x12\x12\n\x0ekProcessKilled\x10\x02\x12\x14\n\x10kProcessCoreDump\x10\x03\x32\xb2\x01\n\x05Initd\x12\x61\n\x10GetProcessStatus\x12%.baidu.galaxy.GetProcessStatusRequest\x1a&.baidu.galaxy.GetProcessStatusResponse\x12\x46\n\x07\x45xecute\x12\x1c.baidu.galaxy.ExecuteRequest\x1a\x1d.baidu.galaxy.ExecuteResponseB\x03\x80\x01\x01')
  ,
  dependencies=[galaxy_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROCESSSTATUS = _descriptor.EnumDescriptor(
  name='ProcessStatus',
  full_name='baidu.galaxy.ProcessStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kProcessRunning', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kProcessTerminate', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kProcessKilled', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kProcessCoreDump', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=705,
  serialized_end=806,
)
_sym_db.RegisterEnumDescriptor(_PROCESSSTATUS)

ProcessStatus = enum_type_wrapper.EnumTypeWrapper(_PROCESSSTATUS)
kProcessRunning = 0
kProcessTerminate = 1
kProcessKilled = 2
kProcessCoreDump = 3



_PROCESSINFOCHECKPOINT = _descriptor.Descriptor(
  name='ProcessInfoCheckpoint',
  full_name='baidu.galaxy.ProcessInfoCheckpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_infos', full_name='baidu.galaxy.ProcessInfoCheckpoint.process_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=116,
)


_PROCESSINFO = _descriptor.Descriptor(
  name='ProcessInfo',
  full_name='baidu.galaxy.ProcessInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='baidu.galaxy.ProcessInfo.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='baidu.galaxy.ProcessInfo.pid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='baidu.galaxy.ProcessInfo.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='baidu.galaxy.ProcessInfo.exit_code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=221,
)


_GETPROCESSSTATUSREQUEST = _descriptor.Descriptor(
  name='GetProcessStatusRequest',
  full_name='baidu.galaxy.GetProcessStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='baidu.galaxy.GetProcessStatusRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=261,
)


_GETPROCESSSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetProcessStatusResponse',
  full_name='baidu.galaxy.GetProcessStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process', full_name='baidu.galaxy.GetProcessStatusResponse.process', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='baidu.galaxy.GetProcessStatusResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=371,
)


_CGROUPPATH = _descriptor.Descriptor(
  name='CgroupPath',
  full_name='baidu.galaxy.CgroupPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subsystem', full_name='baidu.galaxy.CgroupPath.subsystem', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgroup_path', full_name='baidu.galaxy.CgroupPath.cgroup_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=425,
)


_EXECUTEREQUEST = _descriptor.Descriptor(
  name='ExecuteRequest',
  full_name='baidu.galaxy.ExecuteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='baidu.galaxy.ExecuteRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commands', full_name='baidu.galaxy.ExecuteRequest.commands', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='envs', full_name='baidu.galaxy.ExecuteRequest.envs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='baidu.galaxy.ExecuteRequest.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgroup_path', full_name='baidu.galaxy.ExecuteRequest.cgroup_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='baidu.galaxy.ExecuteRequest.user', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pty_file', full_name='baidu.galaxy.ExecuteRequest.pty_file', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chroot_path', full_name='baidu.galaxy.ExecuteRequest.chroot_path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgroups', full_name='baidu.galaxy.ExecuteRequest.cgroups', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=620,
)


_EXECUTERESPONSE = _descriptor.Descriptor(
  name='ExecuteResponse',
  full_name='baidu.galaxy.ExecuteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='baidu.galaxy.ExecuteResponse.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='baidu.galaxy.ExecuteResponse.pid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='baidu.galaxy.ExecuteResponse.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=703,
)

_PROCESSINFOCHECKPOINT.fields_by_name['process_infos'].message_type = _PROCESSINFO
_PROCESSINFO.fields_by_name['status'].enum_type = _PROCESSSTATUS
_GETPROCESSSTATUSRESPONSE.fields_by_name['process'].message_type = _PROCESSINFO
_GETPROCESSSTATUSRESPONSE.fields_by_name['status'].enum_type = galaxy_pb2._STATUS
_EXECUTEREQUEST.fields_by_name['cgroups'].message_type = _CGROUPPATH
_EXECUTERESPONSE.fields_by_name['status'].enum_type = galaxy_pb2._STATUS
DESCRIPTOR.message_types_by_name['ProcessInfoCheckpoint'] = _PROCESSINFOCHECKPOINT
DESCRIPTOR.message_types_by_name['ProcessInfo'] = _PROCESSINFO
DESCRIPTOR.message_types_by_name['GetProcessStatusRequest'] = _GETPROCESSSTATUSREQUEST
DESCRIPTOR.message_types_by_name['GetProcessStatusResponse'] = _GETPROCESSSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['CgroupPath'] = _CGROUPPATH
DESCRIPTOR.message_types_by_name['ExecuteRequest'] = _EXECUTEREQUEST
DESCRIPTOR.message_types_by_name['ExecuteResponse'] = _EXECUTERESPONSE
DESCRIPTOR.enum_types_by_name['ProcessStatus'] = _PROCESSSTATUS

ProcessInfoCheckpoint = _reflection.GeneratedProtocolMessageType('ProcessInfoCheckpoint', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSINFOCHECKPOINT,
  __module__ = 'initd_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.ProcessInfoCheckpoint)
  ))
_sym_db.RegisterMessage(ProcessInfoCheckpoint)

ProcessInfo = _reflection.GeneratedProtocolMessageType('ProcessInfo', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSINFO,
  __module__ = 'initd_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.ProcessInfo)
  ))
_sym_db.RegisterMessage(ProcessInfo)

GetProcessStatusRequest = _reflection.GeneratedProtocolMessageType('GetProcessStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPROCESSSTATUSREQUEST,
  __module__ = 'initd_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.GetProcessStatusRequest)
  ))
_sym_db.RegisterMessage(GetProcessStatusRequest)

GetProcessStatusResponse = _reflection.GeneratedProtocolMessageType('GetProcessStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPROCESSSTATUSRESPONSE,
  __module__ = 'initd_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.GetProcessStatusResponse)
  ))
_sym_db.RegisterMessage(GetProcessStatusResponse)

CgroupPath = _reflection.GeneratedProtocolMessageType('CgroupPath', (_message.Message,), dict(
  DESCRIPTOR = _CGROUPPATH,
  __module__ = 'initd_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.CgroupPath)
  ))
_sym_db.RegisterMessage(CgroupPath)

ExecuteRequest = _reflection.GeneratedProtocolMessageType('ExecuteRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEREQUEST,
  __module__ = 'initd_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.ExecuteRequest)
  ))
_sym_db.RegisterMessage(ExecuteRequest)

ExecuteResponse = _reflection.GeneratedProtocolMessageType('ExecuteResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTERESPONSE,
  __module__ = 'initd_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.ExecuteResponse)
  ))
_sym_db.RegisterMessage(ExecuteResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001'))
# @@protoc_insertion_point(module_scope)
