# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import galaxy_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='baidu.galaxy.proto',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\x12\x62\x61idu.galaxy.proto\x1a\x0cgalaxy.proto\"}\n\x16\x43reateContainerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12\x63ontainer_group_id\x18\x02 \x01(\t\x12;\n\tcontainer\x18\x03 \x01(\x0b\x32(.baidu.galaxy.proto.ContainerDescription\"F\n\x17\x43reateContainerResponse\x12+\n\x04\x63ode\x18\x01 \x01(\x0b\x32\x1d.baidu.galaxy.proto.ErrorCode\"@\n\x16RemoveContainerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12\x63ontainer_group_id\x18\x02 \x01(\t\"F\n\x17RemoveContainerResponse\x12+\n\x04\x63ode\x18\x01 \x01(\x0b\x32\x1d.baidu.galaxy.proto.ErrorCode\"\x17\n\x15ListContainersRequest\"\x81\x01\n\x16ListContainersResponse\x12+\n\x04\x63ode\x18\x01 \x01(\x0b\x32\x1d.baidu.galaxy.proto.ErrorCode\x12:\n\x0f\x63ontainer_infos\x18\x02 \x03(\x0b\x32!.baidu.galaxy.proto.ContainerInfo\"#\n\x0cQueryRequest\x12\x13\n\x0b\x66ull_report\x18\x01 \x01(\x08\"o\n\rQueryResponse\x12+\n\x04\x63ode\x18\x01 \x01(\x0b\x32\x1d.baidu.galaxy.proto.ErrorCode\x12\x31\n\nagent_info\x18\x02 \x01(\x0b\x32\x1d.baidu.galaxy.proto.AgentInfo\"[\n\x0f\x43ontainerMetrix\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x1d\n\x15\x63pu_used_in_millicore\x18\x02 \x01(\x03\x12\x1b\n\x13memory_used_in_byte\x18\x03 \x01(\x03\"\x7f\n\x0c\x43groupMetrix\x12\x1d\n\x15\x63pu_used_in_millicore\x18\x02 \x01(\x03\x12\x1b\n\x13memory_used_in_byte\x18\x03 \x01(\x03\x12\x1a\n\x12\x63ontainer_cpu_time\x18\x04 \x01(\x03\x12\x17\n\x0fsystem_cpu_time\x18\x05 \x01(\x03\x32\x96\x03\n\x05\x41gent\x12j\n\x0f\x43reateContainer\x12*.baidu.galaxy.proto.CreateContainerRequest\x1a+.baidu.galaxy.proto.CreateContainerResponse\x12j\n\x0fRemoveContainer\x12*.baidu.galaxy.proto.RemoveContainerRequest\x1a+.baidu.galaxy.proto.RemoveContainerResponse\x12g\n\x0eListContainers\x12).baidu.galaxy.proto.ListContainersRequest\x1a*.baidu.galaxy.proto.ListContainersResponse\x12L\n\x05Query\x12 .baidu.galaxy.proto.QueryRequest\x1a!.baidu.galaxy.proto.QueryResponseB\x03\x80\x01\x01')
  ,
  dependencies=[galaxy_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CREATECONTAINERREQUEST = _descriptor.Descriptor(
  name='CreateContainerRequest',
  full_name='baidu.galaxy.proto.CreateContainerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='baidu.galaxy.proto.CreateContainerRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_group_id', full_name='baidu.galaxy.proto.CreateContainerRequest.container_group_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container', full_name='baidu.galaxy.proto.CreateContainerRequest.container', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=174,
)


_CREATECONTAINERRESPONSE = _descriptor.Descriptor(
  name='CreateContainerResponse',
  full_name='baidu.galaxy.proto.CreateContainerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='baidu.galaxy.proto.CreateContainerResponse.code', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=246,
)


_REMOVECONTAINERREQUEST = _descriptor.Descriptor(
  name='RemoveContainerRequest',
  full_name='baidu.galaxy.proto.RemoveContainerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='baidu.galaxy.proto.RemoveContainerRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_group_id', full_name='baidu.galaxy.proto.RemoveContainerRequest.container_group_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=312,
)


_REMOVECONTAINERRESPONSE = _descriptor.Descriptor(
  name='RemoveContainerResponse',
  full_name='baidu.galaxy.proto.RemoveContainerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='baidu.galaxy.proto.RemoveContainerResponse.code', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=384,
)


_LISTCONTAINERSREQUEST = _descriptor.Descriptor(
  name='ListContainersRequest',
  full_name='baidu.galaxy.proto.ListContainersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=409,
)


_LISTCONTAINERSRESPONSE = _descriptor.Descriptor(
  name='ListContainersResponse',
  full_name='baidu.galaxy.proto.ListContainersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='baidu.galaxy.proto.ListContainersResponse.code', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_infos', full_name='baidu.galaxy.proto.ListContainersResponse.container_infos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=541,
)


_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='baidu.galaxy.proto.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='full_report', full_name='baidu.galaxy.proto.QueryRequest.full_report', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=578,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='baidu.galaxy.proto.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='baidu.galaxy.proto.QueryResponse.code', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='agent_info', full_name='baidu.galaxy.proto.QueryResponse.agent_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=691,
)


_CONTAINERMETRIX = _descriptor.Descriptor(
  name='ContainerMetrix',
  full_name='baidu.galaxy.proto.ContainerMetrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='baidu.galaxy.proto.ContainerMetrix.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu_used_in_millicore', full_name='baidu.galaxy.proto.ContainerMetrix.cpu_used_in_millicore', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memory_used_in_byte', full_name='baidu.galaxy.proto.ContainerMetrix.memory_used_in_byte', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=693,
  serialized_end=784,
)


_CGROUPMETRIX = _descriptor.Descriptor(
  name='CgroupMetrix',
  full_name='baidu.galaxy.proto.CgroupMetrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_used_in_millicore', full_name='baidu.galaxy.proto.CgroupMetrix.cpu_used_in_millicore', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memory_used_in_byte', full_name='baidu.galaxy.proto.CgroupMetrix.memory_used_in_byte', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_cpu_time', full_name='baidu.galaxy.proto.CgroupMetrix.container_cpu_time', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_cpu_time', full_name='baidu.galaxy.proto.CgroupMetrix.system_cpu_time', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=786,
  serialized_end=913,
)

_CREATECONTAINERREQUEST.fields_by_name['container'].message_type = galaxy_pb2._CONTAINERDESCRIPTION
_CREATECONTAINERRESPONSE.fields_by_name['code'].message_type = galaxy_pb2._ERRORCODE
_REMOVECONTAINERRESPONSE.fields_by_name['code'].message_type = galaxy_pb2._ERRORCODE
_LISTCONTAINERSRESPONSE.fields_by_name['code'].message_type = galaxy_pb2._ERRORCODE
_LISTCONTAINERSRESPONSE.fields_by_name['container_infos'].message_type = galaxy_pb2._CONTAINERINFO
_QUERYRESPONSE.fields_by_name['code'].message_type = galaxy_pb2._ERRORCODE
_QUERYRESPONSE.fields_by_name['agent_info'].message_type = galaxy_pb2._AGENTINFO
DESCRIPTOR.message_types_by_name['CreateContainerRequest'] = _CREATECONTAINERREQUEST
DESCRIPTOR.message_types_by_name['CreateContainerResponse'] = _CREATECONTAINERRESPONSE
DESCRIPTOR.message_types_by_name['RemoveContainerRequest'] = _REMOVECONTAINERREQUEST
DESCRIPTOR.message_types_by_name['RemoveContainerResponse'] = _REMOVECONTAINERRESPONSE
DESCRIPTOR.message_types_by_name['ListContainersRequest'] = _LISTCONTAINERSREQUEST
DESCRIPTOR.message_types_by_name['ListContainersResponse'] = _LISTCONTAINERSRESPONSE
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['ContainerMetrix'] = _CONTAINERMETRIX
DESCRIPTOR.message_types_by_name['CgroupMetrix'] = _CGROUPMETRIX

CreateContainerRequest = _reflection.GeneratedProtocolMessageType('CreateContainerRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATECONTAINERREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.CreateContainerRequest)
  ))
_sym_db.RegisterMessage(CreateContainerRequest)

CreateContainerResponse = _reflection.GeneratedProtocolMessageType('CreateContainerResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATECONTAINERRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.CreateContainerResponse)
  ))
_sym_db.RegisterMessage(CreateContainerResponse)

RemoveContainerRequest = _reflection.GeneratedProtocolMessageType('RemoveContainerRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOVECONTAINERREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.RemoveContainerRequest)
  ))
_sym_db.RegisterMessage(RemoveContainerRequest)

RemoveContainerResponse = _reflection.GeneratedProtocolMessageType('RemoveContainerResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOVECONTAINERRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.RemoveContainerResponse)
  ))
_sym_db.RegisterMessage(RemoveContainerResponse)

ListContainersRequest = _reflection.GeneratedProtocolMessageType('ListContainersRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONTAINERSREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.ListContainersRequest)
  ))
_sym_db.RegisterMessage(ListContainersRequest)

ListContainersResponse = _reflection.GeneratedProtocolMessageType('ListContainersResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONTAINERSRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.ListContainersResponse)
  ))
_sym_db.RegisterMessage(ListContainersResponse)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.QueryRequest)
  ))
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.QueryResponse)
  ))
_sym_db.RegisterMessage(QueryResponse)

ContainerMetrix = _reflection.GeneratedProtocolMessageType('ContainerMetrix', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERMETRIX,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.ContainerMetrix)
  ))
_sym_db.RegisterMessage(ContainerMetrix)

CgroupMetrix = _reflection.GeneratedProtocolMessageType('CgroupMetrix', (_message.Message,), dict(
  DESCRIPTOR = _CGROUPMETRIX,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:baidu.galaxy.proto.CgroupMetrix)
  ))
_sym_db.RegisterMessage(CgroupMetrix)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001'))
# @@protoc_insertion_point(module_scope)
